# Generated by Django 3.2.6 on 2021-08-17 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcoJeju', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='usage_data',
            fields=[
                ('user_waste_id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True, verbose_name='유저 아이디')),
                ('user_waste_city', models.CharField(max_length=20, unique=True, verbose_name='유저 지역')),
                ('user_waste_city_code', models.CharField(max_length=20, unique=True, verbose_name='유저 지역코드')),
                ('user_waste_weight', models.CharField(max_length=20, unique=True, verbose_name='유저 쓰레기 무게')),
                ('user_waste_amount', models.CharField(max_length=20, unique=True, verbose_name='유저 쓰레기 비용')),
            ],
            options={
                'verbose_name': 'waste_data 정보',
                'verbose_name_plural': 'waste_data 정보',
                'db_table': 'waste_data',
            },
        ),
    ]
