# Generated by Django 3.2.6 on 2021-08-18 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcoJeju', '0003_delete_usage_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='disposedata',
            fields=[
                ('dispose_id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True, verbose_name='유저 아이디')),
                ('dispose_city_code', models.CharField(max_length=20, verbose_name='유저 지역코드')),
                ('dispose_weight', models.CharField(max_length=20, verbose_name='유저 쓰레기 무게')),
                ('dispose_amount', models.CharField(max_length=20, verbose_name='유저 쓰레기 비용')),
                ('dispose_date', models.DateTimeField(auto_now_add=True, verbose_name='배출 시간')),
            ],
            options={
                'verbose_name': '개인 배출 정보',
                'verbose_name_plural': '개인 배출 정보',
                'db_table': 'disposedata',
            },
        ),
        migrations.CreateModel(
            name='region',
            fields=[
                ('region_id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True, verbose_name='유저 아이디')),
                ('region_name', models.CharField(max_length=20, verbose_name='유저 이름')),
                ('parent_id', models.CharField(max_length=20, verbose_name=' 아이디')),
            ],
            options={
                'verbose_name': '지역 코드 정보',
                'verbose_name_plural': '지역 코드 정보',
                'db_table': 'region',
            },
        ),
    ]
