# Generated by Django 3.2.6 on 2021-08-18 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EcoJeju', '0004_disposedata_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='parent_id',
            field=models.ForeignKey(db_column='parent_id', on_delete=django.db.models.deletion.PROTECT, to='EcoJeju.region', verbose_name='부모 지역 이름'),
        ),
        migrations.AlterField(
            model_name='region',
            name='region_id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, unique=True, verbose_name='지역 아이디'),
        ),
        migrations.AlterField(
            model_name='region',
            name='region_name',
            field=models.CharField(max_length=20, verbose_name='지역 이름'),
        ),
    ]
