# Generated by Django 3.2.6 on 2021-08-18 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EcoJeju', '0005_auto_20210818_1039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disposedata',
            name='dispose_city_code',
        ),
        migrations.AddField(
            model_name='disposedata',
            name='dispose_region_code',
            field=models.ForeignKey(db_column='dispose_region_code', null=True, on_delete=django.db.models.deletion.PROTECT, to='EcoJeju.region', verbose_name='배출 지역 이름'),
        ),
        migrations.AlterField(
            model_name='region',
            name='parent_id',
            field=models.ForeignKey(db_column=' parent_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='EcoJeju.region', verbose_name='부모 지역 이름'),
        ),
    ]
