# Generated by Django 3.2.6 on 2021-08-18 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcoJeju', '0006_auto_20210818_1051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='region',
            name='parent_id',
        ),
        migrations.AddField(
            model_name='region',
            name='city_name',
            field=models.CharField(max_length=20, null=True, verbose_name='도시 이름'),
        ),
        migrations.AddField(
            model_name='region',
            name='parent_name',
            field=models.CharField(max_length=20, null=True, verbose_name='지역 이름'),
        ),
        migrations.AlterField(
            model_name='disposedata',
            name='dispose_date',
            field=models.DateTimeField(verbose_name='배출 시간'),
        ),
        migrations.AlterField(
            model_name='disposedata',
            name='dispose_region_code',
            field=models.CharField(max_length=20, null=True, verbose_name='구역 코드'),
        ),
        migrations.AlterField(
            model_name='region',
            name='region_name',
            field=models.CharField(max_length=20, verbose_name='구역 이름'),
        ),
    ]
