# Generated by Django 3.2.6 on 2021-08-18 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcoJeju', '0007_auto_20210818_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='disposedata',
            name='dispose_user_id',
            field=models.CharField(max_length=20, null=True, verbose_name='사용 유저 아이디'),
        ),
        migrations.AlterField(
            model_name='disposedata',
            name='dispose_id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, unique=True, verbose_name='배출 아이디'),
        ),
    ]
