# Generated by Django 3.2.6 on 2021-08-18 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcoJeju', '0008_auto_20210818_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disposedata',
            name='dispose_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
