# Generated by Django 3.2.6 on 2021-08-18 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcoJeju', '0009_alter_disposedata_dispose_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disposedata',
            name='dispose_amount',
            field=models.IntegerField(verbose_name='유저 쓰레기 비용'),
        ),
        migrations.AlterField(
            model_name='disposedata',
            name='dispose_region_code',
            field=models.CharField(max_length=20, verbose_name='구역 코드'),
        ),
        migrations.AlterField(
            model_name='disposedata',
            name='dispose_user_id',
            field=models.CharField(max_length=20, verbose_name='사용 유저 아이디'),
        ),
        migrations.AlterField(
            model_name='disposedata',
            name='dispose_weight',
            field=models.IntegerField(verbose_name='유저 쓰레기 무게'),
        ),
    ]
