# Generated by Django 3.2.6 on 2021-08-18 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcoJeju', '0010_auto_20210818_1224'),
    ]

    operations = [
        migrations.CreateModel(
            name='workerarea',
            fields=[
                ('workerarea_id', models.AutoField(primary_key=True, serialize=False)),
                ('worker_id', models.CharField(max_length=20, verbose_name='담당자')),
                ('area_cd', models.CharField(max_length=20, verbose_name='담당 구역 코드')),
            ],
            options={
                'verbose_name': '담당 구역 정보',
                'verbose_name_plural': '담당 구역 정보',
                'db_table': 'workerarea',
            },
        ),
    ]
