# Generated by Django 3.2.6 on 2021-08-19 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcoJeju', '0011_workerarea'),
    ]

    operations = [
        migrations.CreateModel(
            name='wasteprediction',
            fields=[
                ('prediction_id', models.AutoField(primary_key=True, serialize=False)),
                ('region', models.CharField(max_length=20, verbose_name='지역 이름')),
                ('onemonth', models.IntegerField(verbose_name='다음달 예측')),
                ('tw0month', models.IntegerField(verbose_name='다다음달 예측')),
            ],
            options={
                'verbose_name': '음식물 쓰레기 예측 배출량',
                'verbose_name_plural': '음식물 쓰레기 예측 배출량',
                'db_table': 'wasteprediction',
            },
        ),
    ]
